name: snorkeling_full_text
channels:
  - conda-forge
  - pytorch
dependencies:
- pip=20.3.3
- python=3.7.2
- pip:
    - beautifulsoup4==4.6.0
    - black==20.8b1
    - dill==0.3.3
    - flake8==3.8.4
    - gensim==3.8.3
    - intervaltree==3.1.0
    - ipykernel==5.1.3
    - ipywidgets==7.5.1
    - jupyter==1.0.0
    - jupyter_client==5.3.4
    - jupyter_console==6.0.0
    - jupyter_core==4.6.0
    - jupytext==1.9.1
    - llvmlite==0.35.0
    - lxml==4.6.2
    - matplotlib==3.1.1
    - networkx==2.2
    - nltk==3.2.4
    - numpy==1.17.2
    - pandas==1.2.0
    - plotnine==0.7.1
    - requests==2.25.1
    - seaborn==0.11.1
    - scikit-learn==0.21.3
    - scipy==1.3.1 
    - six==1.12.0
    - snorkel==0.9.6
    - spacy==2.3.5
    - sqlalchemy==1.3.22
    - tensorflow==1.14.0
    - tensorboard==1.14.0
    - torch==1.7.1
    - tqdm==4.38.0
    - tika==1.15
    - xlrd==1.1.0
    - xlsxwriter==1.0.4
